### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [PaoloneM/gnrnzh-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by PaoloneM** [comment]
Hi Joe,

  thank you for contacting me. I'll add screenshot, license file and
improve readme until the end of the day (this is my hope).

Paolo

Il lun 11 nov 2019, 21:43 Joe Block <notifications@github.com> ha scritto:

**Comment by unixorn** [comment]
Thanks!

**Comment by unixorn** [comment]
Adding in https://github.com/unixorn/awesome-zsh-plugins/pull/825, thanks
